/*
 * Canonical SFX cue map generator (Manual v2.4 §15.2).
 * Scans assets/audio/sfx/cues/ (Building_Action_Result_01.mp3 canonical names)
 * and emits assets/data/sfx_map.js mapping action ids / pet codes -> cue paths.
 * Data-driven per the manual: re-run after dropping in new cue files —
 *   node scripts/build_sfx_map.js
 * Files that haven't arrived yet simply aren't mapped (game falls back to the
 * generic click/money/eat sounds), so partial deliveries are safe.
 */
var fs = require("fs"), path = require("path");
var DATA = require("../assets/data/gamedata.js");
var ASSUME = require("../js/assumptions.js");

var CUE_DIR = path.join(__dirname, "..", "assets", "audio", "sfx", "cues");
var OUT = path.join(__dirname, "..", "assets", "data", "sfx_map.js");

function norm(s) { return String(s).toLowerCase().replace(/[^a-z0-9]/g, ""); }

// canonical-name fragments that don't literally equal the sheet's action name
var ACTION_OVERRIDES = {
  getorchangejob: "A076",           // "Get / Change Job"
  attendteambuilding: "A079",       // "Attend Team Building Event"
  joinunionmeeting: "A080",         // "...to Fight Evil Corporation"
  vamoose: null
};
// one cue covering a GROUP of actions (building-level shared cues)
var GROUP_CUES = [
  { frag: "aironesupermarketpurchase", ids: ["A026", "A027", "A028", "A029", "A031", "A032"] },
  { frag: "debtstreetcapitalfinancialaction", ids: ["A085", "A086", "A087", "A088", "A090", "A091"] },
];
// audio package spellings that drifted from the painted pet names
var PET_OVERRIDES = { orvilleoverplan: "INTP", vinniethevibescanner: "INFJ" };

var actionsByNorm = {};
DATA.actions.forEach(function (a) { actionsByNorm[norm(a.name)] = a.id; });
var petsByNorm = {};
Object.keys(ASSUME.petNames).forEach(function (code) { petsByNorm[norm(ASSUME.petNames[code])] = code; });

var map = { actions: {}, pets: {} };
var unmatched = [];
fs.readdirSync(CUE_DIR).filter(function (f) { return f.endsWith(".mp3"); }).forEach(function (f) {
  var parts = f.replace(/\.mp3$/, "").split("_");
  var rel = "cues/" + f;
  var whole = norm(f);
  // pets: SharedPets_Interact_<PetName>_01
  if (parts[0] === "SharedPets") {
    var petKey = norm(parts[2]);
    var code = petsByNorm[petKey] || PET_OVERRIDES[petKey] ||
      Object.keys(petsByNorm).filter(function (k) { return k.indexOf(petKey) === 0 || petKey.indexOf(k) === 0; })
        .map(function (k) { return petsByNorm[k]; })[0];
    if (code) map.pets[code] = rel; else unmatched.push(f);
    return;
  }
  // building-level shared cues
  var grouped = GROUP_CUES.filter(function (g) { return whole.indexOf(g.frag) === 0; })[0];
  if (grouped) { grouped.ids.forEach(function (id) { if (!map.actions[id]) map.actions[id] = rel; }); return; }
  // per-action cues: match the Action fragment against the sheet's action names
  var frag = norm(parts[1] || "");
  var id = ACTION_OVERRIDES[frag] || actionsByNorm[frag] ||
    // prefix match ("AttendTeamBuilding" vs "Attend Team Building Event")
    Object.keys(actionsByNorm).filter(function (k) { return k.indexOf(frag) === 0; })
      .map(function (k) { return actionsByNorm[k]; })[0];
  if (id) map.actions[id] = rel; else unmatched.push(f);
});

var body = "// GENERATED by scripts/build_sfx_map.js from assets/audio/sfx/cues/ — do not hand-edit.\n" +
  "// Canonical cue files (Manual v2.4 §15.2): action id / pet code -> cue path.\n" +
  "var PP_SFX_MAP = " + JSON.stringify(map, null, 1) + ";\n" +
  "if (typeof window !== 'undefined') window.PP_SFX_MAP = PP_SFX_MAP;\n" +
  "if (typeof module !== 'undefined') module.exports = PP_SFX_MAP;\n";
fs.writeFileSync(OUT, body);
console.log("action cues:", Object.keys(map.actions).length, "| pet cues:", Object.keys(map.pets).length);
if (unmatched.length) console.log("UNMATCHED:", unmatched.join(", "));
console.log("wrote", OUT);
